### ISSUE TITLE
Custom plugins directory location

### ISSUE THREAD

**Issue by plainspace** [sketchpacks/feedback#1]
Currently I sync plugins across multiple machines with Dropbox and symlinks. Sketchpacks couldn't find my plugins folder.

**Comment by rodnem** [comment]
Neither the standard location, it seems to only display the plugins installed with itself.
It's not cool if you have to uninstall, reinstall just to use Sketchpacks

**Comment by adamkirkwood** [comment]
@plainspace What were the steps you took to accomplish syncing plugins across multiple machines?

Did you hit any flaws in your current method?

Can you describe the experience you expect to allow a person to sync plugins between machines?

**Comment by adamkirkwood** [comment]
@rodnem Since not all plugins are made with the same amount of detail to their `manifest.json` file, we have no way of making sure that each plugin you have is one that we have indexed in our registry, or knowing where to retrieve it's plugin updates.

We just released, v0.4.1 which allows `Import from Sketch Toolbox` as a stepping stone to getting your plugins managed by Sketchpacks quickly.

We plan to investigate more ways to achieve the experience you're describing. 

Thanks again for the feedback!

**Comment by plainspace** [comment]
No flaws. https://www.google.com/search?q=dropbox+sketch+plugins

**Comment by adamkirkwood** [comment]
@plainspace We're nearing `0.6.0` that will have multi-machine syncing support.

However, I'm curious to know if you're only wanting to define your Plugin Installation directory because that is how you are currently working around plugin syncing between machines.

Can you confirm that my assumption is correct?

**Comment by adamkirkwood** [comment]
We won't be supporting custom plugin installation directory. We've decided to solve the problem in a different way for multi-machine syncing (#8).
