### ISSUE TITLE
Terminal Opens and Shows a Console When Using Sketchpacks

### ISSUE THREAD

**Issue by toddjreynolds** [sketchpacks/feedback#17]
I'm not a fan of how my Terminal is opened with Stetchpacks logs. Is that intended? Am I the only one seeing this? 
![screen shot 2017-04-06 at 11 33 45 am](https://cloud.githubusercontent.com/assets/2932865/24767647/e9250086-1abc-11e7-9404-a4a0f749595e.png)

**Comment by adamkirkwood** [comment]
@toddjreynolds Hey there. This issue was addressed in your `v0.5.4`.

Original Issue: https://github.com/sketchpacks/bug-reports/issues/14

**How to resolve**

1. Go to `System Preferences > Users & Groups > Login Items`
2. Remove the old Login Item for Sketchpacks. 
3. Restart Sketchpacks 
4. Enable `Startup at Launch`, which will  add the fixed Login Item for you, which would resolve this issue.

**Comment by toddjreynolds** [comment]
Will do. Thanks.

**Comment by adamkirkwood** [comment]
@toddjreynolds Let me know if this issue persists and I'll investigate further.

Thanks for the feedback.
