### ISSUE TITLE
Include plugins not hosted on GitHub

### ISSUE THREAD

**Issue by mludowise** [sketchpacks/feedback#34]
Currently, there are a number of plugins in the [Plugin Directory](https://github.com/sketchplugins/plugin-directory/) not hosted on GitHub like Sketch Runner. Currently in Sketch Plugin Manager, I allow the user to search and browse for the plugin and link to the plugin's website to install it. If I switch to using the Sketchpacks API, I would like some way to preserve this functionality.

There's only a handful of plugins that aren't hosted on GitHub so it may be worth reaching out to those developers to see how they feel about getting hosted on Sketchpacks. For an up to date list, you can view my [plugin-directory-plus log](https://github.com/mludowise/sketch-plugin-directory-plus/blob/master/log.md) for plugins that have "no repo".

**Comment by willdavis** [comment]
We have plans to open up Sketchpacks to private Github repositories and will be reaching out to the closed source plugins when we get a little closer to being able to deliver that feature.

For plugins not hosted on Github, we do not currently have any plans to support this.  This is because we would need to build a another web hook based integration for any other platforms.

However, if there is significant demand for another git platform, we can look into this again later.
