### ISSUE TITLE
Display current plugins already installed

### ISSUE THREAD

**Issue by AndrewRodgers** [sketchpacks/feedback#4]
Not sure if this is possible, but would be nice to able to see what plugins are already installed when you first run Sketchpacks. 

I have a number of plugins currently installed, yet Sketchpacks doesn't show them via the My Library / Installed view. I assume because I've not installed any directly via the app yet. Thanks.

**Comment by adamkirkwood** [comment]
@AndrewRodgers I agree. But this is also a tricky problem to solve.

Do you currently have most of your plugins installed via Sketch Toolbox?

We don't add in any plugins that haven't been installed via Sketchpacks because we can't guarantee that we'll be able to identify the plugin and its source correctly because not every plugin has a valid manifest.json within the plugins themselves - which makes identifying and linking a tricky problem.

We will be releasing `Import from Sketch Toolbox` this week to help ease the transition though. 😄

**Comment by getflourish** [comment]
First of all, I’m glad to see things moving here! You are onto something! 

Regarding the issue: I have lots of plugins installed and I would really love to see them in Sketchpacks to get started. The import from Toolbox gave me zero results, although I used it to install lots of plugins. 

I understand the difficulties with detecting plugins that you are describing. 

Idea: Maybe Sketchpacks can scan the user’s plugin folder, check for manifest files and show a list of matches and also the ones that could not be detected. 

Users could then choose to "re-install" all existing plugins that are available in the registry and get the latest version. For others, a list with "unmatched" plugins, could help users to search for those  plugins manually.

**Comment by mijlee** [comment]
I think this is the only missing piece for me. The app seems to work pretty well and not that Toolbox seems to have been abandoned I was really glad to see a new kid on the block. For now I’ll just delete the plugins and reinstall but as someone who is quite often on different machines it would be great if there was a fix for this.

**Comment by adamkirkwood** [comment]
@AndrewRodgers @mijlee @getflourish You'll find this issue fixed in `0.5.7`.

As always, thanks for the feedback!
